# Generated by Django 5.2.4 on 2025-08-02 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='travel.travelstyle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_style_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
