# Generated by Django 5.2.4 on 2025-08-03 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proximate_nature', models.FloatField()),
                ('thrill_activities', models.FloatField()),
                ('average_cost', models.FloatField()),
                ('cultural_sites', models.FloatField()),
                ('spa_facilities', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usertravelstyle',
            name='travel_style',
        ),
        migrations.AlterField(
            model_name='usertravelstyle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('duration_hours', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel.destination')),
            ],
        ),
        migrations.AddField(
            model_name='usertravelstyle',
            name='travel_style',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='travel.travelstyle'),
        ),
        migrations.CreateModel(
            name='StyleParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="مثلاّ 'nature', 'thrill', 'budget'", max_length=100)),
                ('weight', models.FloatField(help_text='وزن پارامتر در امتیازدهی')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='travel.travelstyle')),
            ],
            options={
                'unique_together': {('style', 'key')},
            },
        ),
    ]
