# Generated by Django 5.2.4 on 2025-08-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_usertravelstyle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertravelstyle',
            name='travel_style',
            field=models.ManyToManyField(related_name='users', to='travel.travelstyle'),
        ),
    ]
