# Generated by Django 5.2.4 on 2025-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_usertravelstyle_travel_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='TravelStyle',
            field=models.ManyToManyField(related_name='destinations', to='travel.travelstyle'),
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
