# Generated by Django 5.1.3 on 2025-08-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_destination_travelstyle_destination_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='average_cost',
        ),
    ]
