# Generated by Django 5.1.3 on 2025-08-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_destination_average_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='TravelStyle',
            new_name='travel_styles',
        ),
    ]
